apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam-as
  template:
    metadata:
      labels:
        app: ipam-as
    spec:
      containers:
        - name: ipam-as
          image: akzrepo/ipam-as:test1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          command:
            - /bin/ipam-as